# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mplfinance as mpf
import pandas as pd
import requests


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 620)
        Dialog.setStyleSheet("background-color:rgb(43, 83, 214)")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 20, 341, 61))
        self.label.setStyleSheet("color:rgb(255, 255, 255);font-size:28pt;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 71, 41))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);font-size:18pt;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 231, 41))
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);font-size:20pt;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 80, 361, 61))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255);font-size:28pt;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 360, 271, 41))
        self.label_5.setStyleSheet("color:rgb(255, 255, 255);font-size:20pt;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 450, 131, 41))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);font-size:20pt;")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QTextEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(320, 180, 161, 41))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 270, 161, 41))
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 360, 161, 41))
        self.lineEdit_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 450, 161, 41))
        self.lineEdit_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 540, 100, 30))
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255)rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.ok)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    
    def ok(self):
        strttime = self.lineEdit.toPlainText()
        basecrncy = self.lineEdit_2.toPlainText()
        comparecrncy = self.lineEdit_3.toPlainText()
        intrvl = self.lineEdit_4.toPlainText()
        self.get_candles(strttime, basecrncy, comparecrncy, intrvl)


    def get_candles(self, start_time, base_currency, compare_currency, interval):
        url = f'https://dev-api.shrimpy.io/v1/exchanges/binance/candles'
        payload = {'interval': interval, 
                'baseTradingSymbol': base_currency, 
                'quoteTradingSymbol': compare_currency, 
                'startTime': start_time}

        response = requests.get(url, params = payload)
        data = response.json()    

        open_price = []
        close_price = []
        low_price = []
        high_price = []
        time_price = []

        for candle in data:
            open_price.append(float(candle['open'])) 
            high_price.append(float(candle['high']))
            low_price.append(float(candle['low']))
            close_price.append(float(candle['close']))
            time_price.append(candle['time'])

        raw_data = {'Date': pd.DatetimeIndex(time_price),
                    'Open': open_price,
                    'High': high_price,
                    'Low': low_price,
                    'Close': close_price}
    
        df = pd.DataFrame(raw_data).set_index('Date')

        print(df)

        mpf.plot(df, type = 'candle', style = 'charles', title =  base_currency, ylabel = f'Price in {compare_currency}')
        mpf.show()

        return df


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", " Cryptocurrency "))
        self.label_2.setText(_translate("Dialog", "Time"))
        self.label_3.setText(_translate("Dialog", "base currency"))
        self.label_4.setText(_translate("Dialog", "Candlestick chart"))
        self.label_5.setText(_translate("Dialog", "compare currency"))
        self.label_6.setText(_translate("Dialog", "interval"))
        self.pushButton_2.setText(_translate("Dialog", "OK"))

  
  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

